class CrowdinAT5 < Formula
  desc "Command-line tool to manage and synchronize localization resources with Crowdin"
  homepage "https://crowdin.github.io/crowdin-cli/"
  version "5.3.0"
  license "MIT"
  version_scheme 1

  # Generated by the publish workflow from .github/templates/crowdin@5.rb.erb.
  # Edit the template, not this file.
  on_macos do
    on_arm do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.3.0/crowdin-darwin-arm64"
      sha256 "8ab3836fd6f22834c9cb65c95463e137c5ec84dd56a0dadc529952a68d3ba367"
    end
    on_intel do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.3.0/crowdin-darwin-x64"
      sha256 "53ade037eb42fafdf6b0cafa55578d7f65c98380edcadf507d1f6354319e044d"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.3.0/crowdin-linux-arm64"
      sha256 "72a92068230ad740d2ae678429b60e83170d258f9e4fa14b8ad91a8e2cba4b7a"
    end
    on_intel do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.3.0/crowdin-linux-x64"
      sha256 "d3f8e74471b98d47c0964e85c992a04eb411d06138c4239118a4c94d29e3e9e4"
    end
  end

  livecheck do
    skip "Binary releases updated by CI"
  end

  conflicts_with "crowdin", because: "both install a `crowdin` executable"

  def install
    binary = Dir["crowdin-*"].fetch(0)
    bin.install binary => "crowdin"
    chmod 0555, bin/"crowdin"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/crowdin --version").strip
  end
end
