class CrowdinAT5 < Formula
  desc "Command-line tool to manage and synchronize localization resources with Crowdin"
  homepage "https://crowdin.github.io/crowdin-cli/"
  version "5.1.0"
  license "MIT"
  version_scheme 1

  # Generated by the publish workflow from .github/templates/crowdin@5.rb.erb.
  # Edit the template, not this file.
  on_macos do
    on_arm do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.1.0/crowdin-darwin-arm64"
      sha256 "7c6554f08740d96c32bd347f87da0c1c71e07b872b4e7dd909b790b060909b1f"
    end
    on_intel do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.1.0/crowdin-darwin-x64"
      sha256 "7fbb8076de385b675323ee0f1701492825826d3af8540de931659cfbae7cb92c"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.1.0/crowdin-linux-arm64"
      sha256 "a90283123908a1e2b31a645a98251b92610f30ecfbd3e54542a8bdd240f2ce9c"
    end
    on_intel do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.1.0/crowdin-linux-x64"
      sha256 "9ac1771dd284f5ef0cf1ecac7ea4c8293242ad98ace697c33bcc4e7f7f989bbc"
    end
  end

  livecheck do
    skip "Binary releases updated by CI"
  end

  conflicts_with "crowdin", because: "both install a `crowdin` executable"

  def install
    binary = Dir["crowdin-*"].fetch(0)
    bin.install binary => "crowdin"
    chmod 0555, bin/"crowdin"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/crowdin --version").strip
  end
end
