class CrowdinAT5 < Formula
  desc "Command-line tool to manage and synchronize localization resources with Crowdin"
  homepage "https://crowdin.github.io/crowdin-cli/"
  version "5.0.2"
  license "MIT"
  version_scheme 1

  # Generated by the publish workflow from .github/templates/crowdin@5.rb.erb.
  # Edit the template, not this file.
  on_macos do
    on_arm do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.0.2/crowdin-darwin-arm64"
      sha256 "8137c048dec5bcafed5595c4f571ca3f7ce241515fc4d40b1f2700049396658d"
    end
    on_intel do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.0.2/crowdin-darwin-x64"
      sha256 "ec9d66cf442db6db1fe1f0183d1ad0826770e79ecdadff6349c7b3864f87f115"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.0.2/crowdin-linux-arm64"
      sha256 "99b1eb59ef464d03eb28ec7f281bbce825360897b68b3c34a4b5afb0a8f1daea"
    end
    on_intel do
      url "https://github.com/crowdin/crowdin-cli/releases/download/5.0.2/crowdin-linux-x64"
      sha256 "1806cdbc4c539ace92cb68e9fd8f41de3bf319f11de28f6137cf0e23a7929b50"
    end
  end

  livecheck do
    skip "Binary releases updated by CI"
  end

  conflicts_with "crowdin", because: "both install a `crowdin` executable"

  def install
    binary = Dir["crowdin-*"].fetch(0)
    bin.install binary => "crowdin"
    chmod 0555, bin/"crowdin"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/crowdin --version").strip
  end
end
