name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version number (in x.x.x format)'
        required: true

permissions:
  contents: write

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest

    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          create-pullrequest: false
          formula-path: Formula/crowdin@4.rb
          tag-name: ${{ github.event.inputs.version }}
          download-url: https://github.com/crowdin/crowdin-cli/releases/download/${{ github.event.inputs.version }}/crowdin-cli.zip
          homebrew-tap: crowdin/homebrew-crowdin
        env:
          COMMITTER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
